pipeline {
    agent any
    stages {
        stage('Print Variables') {
            steps {
                script {
                    echo "Action: ${env.OBJECT_ATTRIBUTES_ACTION}"
                    echo "Object: ${env.OBJECT_ATTRIBUTES_OBJECT}"
                }
            }
        }
    }
}