pipeline {
    agent any

    stages {
        stage('Merge Opened') {

            steps {
                     echo "${env.MERGE_STATUS}"
                     echo "${env.STATE}"
            }
        }
        stage('Merge Completed') {

            steps {
                script {
                     echo "${env.MERGE_STATUS}"
                     echo "${env.STATE}"
                }
            }
        }
    }
}
